server:
  port: 8051
management: 
  security:
    enabled: false
spring:
  application:
    name: provider-network
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.12.12:3306/ct_appmarket?useUnicode=true&amp;characterEncoding=UTF-8
    username: ky
    password: ky_2017
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT NOW()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate: 
      ddl-auto: validate
  rabbitmq:
      host: 192.168.12.16
      port: 5672
      username: admin
      password: birdgame2015
message:
  http:
    url: http://ip:9091/get/user/5-1